/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;

import java.awt.Color;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author NABILA
 */
public class Admin extends javax.swing.JFrame {
   Connection con;
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }
    
    public Admin(String username){
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        nama.setText(username);
        DateFormat df = new SimpleDateFormat("dd-MM-yyy");
        Date today = Calendar.getInstance().getTime();        
        String reportDate = df.format(today);
        tgl_ex.setText(reportDate);
        new CambiaPanel(centerpanel, new p_anggota());
        onClick(anggota);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    
     private void onClick(JPanel panel){
        panel.setBackground(new Color(0,255,255));
    }
    
    private void onLeaveClick(JPanel panel){
        panel.setBackground(new Color(0,204,204));
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        sidepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        anggota = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pendataan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pembukuan = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        laporan = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        pendataanMaster = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        centerpanel = new javax.swing.JPanel();
        headpanel = new javax.swing.JPanel();
        admin_form = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        tgl_ex = new javax.swing.JLabel();
        signout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 153, 204));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-female-profile-96.png"))); // NOI18N
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 84));

        anggota.setBackground(new java.awt.Color(0, 204, 204));
        anggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anggotaMouseClicked(evt);
            }
        });
        anggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-staff-skin-type-7-48.png"))); // NOI18N
        anggota.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 150, 50));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pegawai");
        jLabel4.setInheritsPopupMenu(false);
        anggota.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, -1));

        pembayaran.setBackground(new java.awt.Color(0, 204, 204));
        pembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembayaranMouseClicked(evt);
            }
        });
        pembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash-48.png"))); // NOI18N
        pembayaran.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Penjualan");
        jLabel6.setInheritsPopupMenu(false);
        pembayaran.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, -1));

        pendataan.setBackground(new java.awt.Color(0, 204, 204));
        pendataan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendataan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendataanMouseClicked(evt);
            }
        });
        pendataan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-row-48 (1).png"))); // NOI18N
        pendataan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pendataan");
        jLabel8.setInheritsPopupMenu(false);
        pendataan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(pendataan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, -1));

        pembukuan.setBackground(new java.awt.Color(0, 204, 204));
        pembukuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pembukuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembukuanMouseClicked(evt);
            }
        });
        pembukuan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-binder-48.png"))); // NOI18N
        pembukuan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pembukuan");
        jLabel10.setInheritsPopupMenu(false);
        pembukuan.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(pembukuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 150, -1));

        pelanggan.setBackground(new java.awt.Color(0, 204, 204));
        pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pelangganMouseClicked(evt);
            }
        });
        pelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-users-48.png"))); // NOI18N
        pelanggan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Pelanggan Antibiotik");
        jLabel31.setInheritsPopupMenu(false);
        pelanggan.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 150, -1));

        laporan.setBackground(new java.awt.Color(0, 204, 204));
        laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        laporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-align-text-top-48.png"))); // NOI18N
        laporan.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel34.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Laporan");
        jLabel34.setInheritsPopupMenu(false);
        laporan.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, -1));

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setText("Pendataan Barang");
        nama.setPreferredSize(new java.awt.Dimension(587, 450));
        sidepanel.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 20));

        pendataanMaster.setBackground(new java.awt.Color(0, 204, 204));
        pendataanMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pendataanMaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendataanMasterMouseClicked(evt);
            }
        });
        pendataanMaster.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-database-administrator-48.png"))); // NOI18N
        pendataanMaster.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pendataan Master");
        jLabel13.setInheritsPopupMenu(false);
        pendataanMaster.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, -1));

        sidepanel.add(pendataanMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 150, 70));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 630));

        centerpanel.setLayout(new javax.swing.BoxLayout(centerpanel, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(centerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 800, 630));

        headpanel.setBackground(new java.awt.Color(255, 255, 255));

        admin_form.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        admin_form.setForeground(new java.awt.Color(0, 153, 204));
        admin_form.setText("ADMIN FORM");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-24 (3).png"))); // NOI18N
        icon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconMouseClicked(evt);
            }
        });

        tgl_ex.setFont(new java.awt.Font("Bell Gothic Std Light", 1, 24)); // NOI18N
        tgl_ex.setForeground(new java.awt.Color(0, 153, 204));
        tgl_ex.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        signout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutMouseClicked(evt);
            }
        });
        signout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("LOG OUT");
        signout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 110, 20));

        javax.swing.GroupLayout headpanelLayout = new javax.swing.GroupLayout(headpanel);
        headpanel.setLayout(headpanelLayout);
        headpanelLayout.setHorizontalGroup(
            headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgl_ex, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246)
                .addComponent(admin_form)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(signout, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(icon)
                .addGap(19, 19, 19))
        );
        headpanelLayout.setVerticalGroup(
            headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tgl_ex, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admin_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(headpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutMouseClicked

    private void pembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembayaranMouseClicked
       // TODO add your handling code here:
        String nm = nama.getText();
       new CambiaPanel(centerpanel, new JFPenjualan(nm));
         onClick(pembayaran);
        onLeaveClick(pendataan);
        onLeaveClick(pembukuan);
        onLeaveClick(anggota);
        onLeaveClick(pendataanMaster);
        onLeaveClick(laporan);
        onLeaveClick(pelanggan);
    }//GEN-LAST:event_pembayaranMouseClicked

    private void pendataanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendataanMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_pendataan());
        onLeaveClick(pembayaran);
        onClick(pendataan);
        onLeaveClick(pembukuan);
        onLeaveClick(anggota);
        onLeaveClick(laporan);
        onLeaveClick(pendataanMaster);
        onLeaveClick(pelanggan);
    }//GEN-LAST:event_pendataanMouseClicked

    private void pembukuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembukuanMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_pembukuan());
        onLeaveClick(pembayaran);
        onLeaveClick(pendataan);
        onClick(pembukuan);
        onLeaveClick(anggota);
        onLeaveClick(laporan);
        onLeaveClick(pelanggan);
        onLeaveClick(pendataanMaster);
    }//GEN-LAST:event_pembukuanMouseClicked

    private void anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anggotaMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_anggota());
        onLeaveClick(pembayaran);
        onLeaveClick(pendataan);
        onLeaveClick(pembukuan);
        onClick(anggota);
        onLeaveClick(pendataanMaster);
        onLeaveClick(laporan);
        onLeaveClick(pelanggan);
    }//GEN-LAST:event_anggotaMouseClicked

    private void pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pelangganMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_pelanggan());
        onLeaveClick(pembayaran);
        onLeaveClick(pendataan);
        onLeaveClick(pembukuan);
        onLeaveClick(anggota);
        onLeaveClick(laporan);
        onLeaveClick(pendataanMaster);
        onClick(pelanggan);
    }//GEN-LAST:event_pelangganMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_laporan());
        onLeaveClick(pembayaran);
        onLeaveClick(pendataan);
        onLeaveClick(pembukuan);
        onClick(laporan);
        onLeaveClick(anggota);
        onLeaveClick(pelanggan);
        onLeaveClick(pendataanMaster);
    }//GEN-LAST:event_laporanMouseClicked

    private void iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_iconMouseClicked

    private void pendataanMasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendataanMasterMouseClicked
        // TODO add your handling code here:
        new CambiaPanel(centerpanel, new p_masterData());
        onLeaveClick(pembayaran);
        onLeaveClick(pendataan);
        onLeaveClick(pembukuan);
        onClick(pendataanMaster);
        onLeaveClick(anggota);
        onLeaveClick(pelanggan);
        onLeaveClick(laporan);
    }//GEN-LAST:event_pendataanMasterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_form;
    private javax.swing.JPanel anggota;
    private javax.swing.JPanel centerpanel;
    private javax.swing.JPanel headpanel;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel laporan;
    private javax.swing.JLabel nama;
    private javax.swing.JPanel pelanggan;
    private javax.swing.JPanel pembayaran;
    private javax.swing.JPanel pembukuan;
    private javax.swing.JPanel pendataan;
    private javax.swing.JPanel pendataanMaster;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel signout;
    private javax.swing.JLabel tgl_ex;
    // End of variables declaration//GEN-END:variables
}

