/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;

import Koneksi.Koneksi;
import com.mysql.jdbc.Statement;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author NABILA
 */
public class Daftar extends javax.swing.JFrame {
    Connection con;
    /**
     * Creates new form Daftar
     */
   
   public Daftar() {
        initComponents();
        dt_anggota();
   }

    public Daftar(String username) {
        initComponents();
        ubah.setText(username);
        MouseEvent evt = null;
        ubahMousePressed(evt);
        dt_anggota1();
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubah = new javax.swing.JTextField();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        icon_close = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        nama_depan = new javax.swing.JLabel();
        nama_belakang = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        option = new javax.swing.JLabel();
        txtNamaDepan = new javax.swing.JTextField();
        txtNamaBelakang = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        comboOption = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnggota = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        btn_Edit = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        ubah.setEditable(false);
        ubah.setEnabled(false);
        ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ubahMousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("FORM TAMBAH PEGAWAI");

        icon_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-24 (3).png"))); // NOI18N
        icon_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175)
                .addComponent(icon_close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(icon_close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        centerPanel.setEnabled(false);

        nama_depan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_depan.setText("Nama Depan");

        nama_belakang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_belakang.setText("Nama Belakang");

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setText("Username");

        password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password.setText("Password");

        option.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        option.setText("Option");

        txtNamaDepan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaDepanActionPerformed(evt);
            }
        });

        comboOption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-", "Admin", "Owner" }));

        tblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Depan", "Nama Belakang", "Username", "Password", "Option"
            }
        ));
        tblAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAnggota);

        btn_Add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-24.png"))); // NOI18N
        btn_Add.setText("Tambah");
        btn_Add.setIconTextGap(10);
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-checkmark-24.png"))); // NOI18N
        btn_Edit.setText("Selesai");
        btn_Edit.setIconTextGap(10);
        btn_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditActionPerformed(evt);
            }
        });

        btn_Clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-clear-symbol-24.png"))); // NOI18N
        btn_Clear.setText("Hapus");
        btn_Clear.setIconTextGap(10);
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-24.png"))); // NOI18N
        btn_Delete.setText("Buang");
        btn_Delete.setIconTextGap(10);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-arrow-pointing-left-24.png"))); // NOI18N
        btn_Back.setText("Kembali");
        btn_Back.setIconTextGap(10);
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(centerPanelLayout.createSequentialGroup()
                                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(centerPanelLayout.createSequentialGroup()
                                        .addComponent(nama_belakang)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                        .addComponent(txtNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(centerPanelLayout.createSequentialGroup()
                                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nama_depan)
                                            .addComponent(username)
                                            .addComponent(option)
                                            .addComponent(password))
                                        .addGap(35, 35, 35)
                                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassword)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(txtNamaDepan)
                                            .addComponent(comboOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(133, 133, 133)
                                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(centerPanelLayout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(btn_Add)
                            .addGap(127, 127, 127)
                            .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                            .addGap(613, 613, 613)
                            .addComponent(btn_Back))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_depan)
                            .addComponent(txtNamaDepan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_belakang)
                            .addComponent(txtNamaBelakang, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(option)
                            .addComponent(comboOption, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(centerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void icon_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_icon_closeMouseClicked

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        String fn = txtNamaDepan.getText();
        String ln = txtNamaBelakang.getText();
        String un = txtUsername.getText();
        String psw = txtPassword.getText();
        String ot = (String) comboOption.getSelectedItem();
        
        if (fn.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Nama Depan Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        if (ln.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Nama Belakang Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        if (un.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Username Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        if (psw.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Password Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        if (ot.equals("")) {
            JOptionPane.showMessageDialog(null, "Option Tidak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

       try{
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            com.mysql.jdbc.Statement st = (com.mysql.jdbc.Statement) con.createStatement();
            ResultSet rs = st.executeQuery("Select * from login where username = '"+un+"'");
            rs.next();
            if (rs.getRow()>0){
                st.close();
                rs.close();
                JOptionPane.showMessageDialog(null,"Username Sudah Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
            } else  {
                st.close();
                rs.close();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into login (firstname,lastname,username,password,options) values(?,?,?,?,?)");
                ps.setString(1, fn);
                ps.setString(2, ln);
                ps.setString(3, un);
                ps.setString(4, psw);
                 ps.setString(5, ot);
                ps.executeUpdate();
                con.close();
                dt_anggota();
            }
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Data sudah tersimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        }
       txtNamaDepan.setText("");
        txtNamaBelakang.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        comboOption.setSelectedItem("-Select-");
       
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        txtNamaDepan.setText("");
        txtNamaBelakang.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        comboOption.setSelectedItem("-Select-");
        dt_anggota();
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        String un = txtUsername.getText();
       int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini? '"+un+"'", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
       if (ok == 0) {
           try{
                    Statement statement = (Statement) Koneksi.getConnection().createStatement();
                    statement.executeUpdate("delete from  login WHERE username='"+un+"' ");
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    
                }catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
                }}dt_anggota();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditActionPerformed
        // TODO add your handling code here:
        String fn = txtNamaDepan.getText();
        String ln = txtNamaBelakang.getText();
        String un = txtUsername.getText();
        String psw = txtPassword.getText();
        String ot = (String) comboOption.getSelectedItem();
        if (un.equals("")) {
            JOptionPane.showMessageDialog(null, "Kolom Username TIdak Boleh Kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else{
            int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Untuk Update Data ini?","Confirmation",JOptionPane.YES_NO_OPTION);
            try
            {
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
                String sql="update login set firstname=?, lastname=?, password=?, options=? where username='"+un+"'";
                PreparedStatement st=con.prepareStatement(sql);
                if(ok==0)
                {
                    try
                    {
                        st.setString(1,fn);
                        st.setString(2,ln);
                        st.setString(3,psw);
                        st.setString(4,ot);
                        st.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Update Data Sukses");
                        dt_anggota();
                    }catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null, "Update Data Gagal");
                    }
                }
            }catch (Exception e){

            }}
    }//GEN-LAST:event_btn_EditActionPerformed

    private void tblAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnggotaMouseClicked
        // TODO add your handling code here:
        int i = tblAnggota.getSelectedRow();
        if(i== -1){
            return;
        }
            String fn = (String) tblAnggota.getValueAt(i, 0);
            txtNamaDepan.setText(fn);
            String ln = (String) tblAnggota.getValueAt(i, 1);
            txtNamaBelakang.setText(ln);
            String un = (String) tblAnggota.getValueAt(i, 2);
            txtUsername.setText(un);
            String psw = (String) tblAnggota.getValueAt(i, 3);
            txtPassword.setText(psw);
            String ot = (String) tblAnggota.getValueAt(i, 4);
            comboOption.setSelectedItem(ot);
    }//GEN-LAST:event_tblAnggotaMouseClicked

    private void ubahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahMousePressed
        // TODO add your handling code here:
        try {
            com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from login where username = '"+ubah.getText()+"'");
            if (rs.next()) {
                txtNamaDepan.setText(rs.getString("firstname"));
                txtNamaBelakang.setText(rs.getString("lastname"));
                txtUsername.setText(rs.getString("username"));
                txtPassword.setText(rs.getString("password"));
                comboOption.setSelectedItem(rs.getString("options"));
            } else {
            }
            
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(p_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ubahMousePressed

    private void txtNamaDepanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaDepanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaDepanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Edit;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox comboOption;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel icon_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama_belakang;
    private javax.swing.JLabel nama_depan;
    private javax.swing.JLabel option;
    private javax.swing.JLabel password;
    private javax.swing.JTable tblAnggota;
    private javax.swing.JTextField txtNamaBelakang;
    private javax.swing.JTextField txtNamaDepan;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField ubah;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
private DefaultTableModel Daftar;
    private void dt_anggota() {
        ubah.setText(null);
        Object kolom []={"Firstname", "Lastname","Username","password","Options"};
        Daftar=new DefaultTableModel(null,kolom);
        tblAnggota.setModel(Daftar);
        jScrollPane1.getViewport().add(tblAnggota,null);
        try {
            con = Koneksi.getConnection();
            String sql = "" + "SELECT * FROM login";
            java.sql.Statement stat=con.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                String Nidn=res.getString("firstname");
                String Nama=res.getString("lastname");
                String Jabatan=res.getString("username");
                String psw=res.getString("password");
                String Alamat=res.getString("options");
                Object [] data={Nidn,Nama,Jabatan,psw,Alamat};
                Daftar.addRow(data);}
            tblAnggota.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(4).setPreferredWidth(20);
        } catch (Exception e) {
        }
    }
    
    private DefaultTableModel Daftar1;
    private void dt_anggota1() {
        ubah.setText(null);
        Object kolom []={"Firstname", "Lastname","Username","password","Options"};
        Daftar1=new DefaultTableModel(null,kolom);
        tblAnggota.setModel(Daftar1);
        jScrollPane1.getViewport().add(tblAnggota,null);
        try {
            con = Koneksi.getConnection();
            String sql = "" + "SELECT * FROM login where username";
            java.sql.Statement stat=con.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                String Nidn=res.getString("firstname");
                String Nama=res.getString("lastname");
                String Jabatan=res.getString("username");
                String psw=res.getString("password");
                String Alamat=res.getString("options");
                Object [] data={Nidn,Nama,Jabatan,psw,Alamat};
                Daftar1.addRow(data);}
            tblAnggota.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(4).setPreferredWidth(20);
        } catch (Exception e) {
        }
    }

}
