/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import static groovy.ui.text.FindReplaceUtility.dispose;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author NABILA
 */
public class JFBarang extends javax.swing.JFrame {

    /**
     * Creates new form JFBarang
     */
    String s;
    
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(labelImageDesplay.getWidth(), labelImageDesplay.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
 
    public JFBarang() {
        initComponents();
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(false);
        this.setResizable(false);
    }
    
    public JTextField getKode(){ return jTextField1; }
    public JTextField getNama(){ return jTextField2; }
    public JTextArea getKeterangan(){ return jTextField3; }
    public JLabel getID(){ return ID; }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnImageBrowser = new javax.swing.JButton();
        btnImageInsert = new javax.swing.JButton();
        ID = new javax.swing.JLabel();
        btnImageDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        labelImageDesplay = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField3 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(415, 180));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImageBrowser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImageBrowser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-google-images-24.png"))); // NOI18N
        btnImageBrowser.setText("Tambah Gambar");
        btnImageBrowser.setIconTextGap(10);
        btnImageBrowser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageBrowserActionPerformed(evt);
            }
        });
        jPanel1.add(btnImageBrowser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 160, -1));

        btnImageInsert.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImageInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-24.png"))); // NOI18N
        btnImageInsert.setText("Tambah");
        btnImageInsert.setIconTextGap(10);
        btnImageInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnImageInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 110, -1));
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 29, -1));

        btnImageDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnImageDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-24.png"))); // NOI18N
        btnImageDelete.setText("Hapus");
        btnImageDelete.setIconTextGap(10);
        btnImageDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnImageDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kode");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 290, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Keterangan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, -1));

        labelImageDesplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(labelImageDesplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 220, 290));

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-window-24.png"))); // NOI18N
        jButton6.setText("Keluar");
        jButton6.setIconTextGap(10);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, -1));

        jTextField3.setColumns(20);
        jTextField3.setRows(5);
        jScrollPane1.setViewportView(jTextField3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, 150));

        jPanel2.setBackground(new java.awt.Color(38, 86, 186));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM BARANG");
        jPanel2.add(jLabel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImageBrowserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageBrowserActionPerformed
        JFileChooser chooser = new JFileChooser(System.getProperty("user.home"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setFileFilter(new FileNameExtensionFilter("jpg|png|bmp", "jpg","png","bmp"));
        if(chooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File file=chooser.getSelectedFile();
            File selectedFile = chooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            labelImageDesplay.setIcon(ResizeImage(path));
            s = path;}
    }//GEN-LAST:event_btnImageBrowserActionPerformed

    private void btnImageInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageInsertActionPerformed
        try{
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from barang where kode = '"+jTextField1.getText()+"'");
            rs.next();
            if (rs.getRow()>0){
                st.close();
                rs.close();
                JOptionPane.showMessageDialog(null,"Kode Barang Sudah Ada","Informasi",JOptionPane.INFORMATION_MESSAGE);
            } else  {
                st.close();
                rs.close();
                PreparedStatement ps = (PreparedStatement) con.prepareStatement("insert into barang(kode,nama,keterangan,image,harga,jumlah) values(?,?,?,?,?,?)");
                InputStream is = new FileInputStream(new File(s));
                ps.setString(1, jTextField1.getText());
                ps.setString(2, jTextField2.getText());
                ps.setString(3, jTextField3.getText());
                ps.setBlob(4,is);
                ps.setString(5,"0");
                ps.setString(6,"0");
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null,"Data Barang sudah tersimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                labelImageDesplay.setIcon(null);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnImageInsertActionPerformed

    private void btnImageDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageDeleteActionPerformed
        try
        {
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("Delete from barang where kode = '"+jTextField1.getText()+"'");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            labelImageDesplay.setIcon(null);
            JOptionPane.showMessageDialog(null,"Data Delete......!!!");

            con.close();

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnImageDeleteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try {
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from barang where kode = '"+jTextField1.getText()+"'");
            if (rs.next()) {
                byte[] img = rs.getBytes("image");
                ImageIcon image = new ImageIcon(img);
                jTextField2.setText(rs.getString("nama"));
                jTextField3.setText(rs.getString("keterangan"));
                Image myImage = image.getImage();
                Image newImage = myImage.getScaledInstance(labelImageDesplay.getWidth(), labelImageDesplay.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon myImageL = new ImageIcon(newImage);
                labelImageDesplay.setIcon(myImageL);

            } else {
            jTextField2.setText("");
            jTextField3.setText("");
            labelImageDesplay.setIcon(null);
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(p_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton btnImageBrowser;
    private javax.swing.JButton btnImageDelete;
    private javax.swing.JButton btnImageInsert;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea jTextField3;
    private javax.swing.JLabel labelImageDesplay;
    // End of variables declaration//GEN-END:variables
}
