/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Koneksi.Koneksi;
import controller.c_tpenjualan;
import static groovy.ui.text.FindReplaceUtility.dispose;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NABILA
 */
public class JFPenjualan extends javax.swing.JPanel {

    c_tpenjualan penjualan;
    Connection conn;
    Statement st;
    ResultSet rs;
    /**
     * Creates new form JFPenjualan
     */
    
    public JFPenjualan(String nm){
        initComponents();
        penjualan = new c_tpenjualan(this);
        penjualan.isiTabelt();
        penjualan.isiTabeltmp();
        penjualan.removeall();
        jLabel2.setText(nm);
        siapIsi(false);
        tombolNormal();
        // Tanggal
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date today = Calendar.getInstance().getTime();        
        String reportDate = df.format(today);
        txtTgl.setText(reportDate);
    }
    
    
    public JTable getDataTableT(){ return jTable1; }
    public JTable getDataTableTmp(){ return jTable2; }
    public JTextField getNotrans() { return txtNoTf; }
    public JTextField getTanggal(){ return txtTgl; }
    public JTextField getKodeBarang(){ return txtKodeBarang; }
    public JTextField getNamaBarang(){ return txtNamaBarang; }
    public JTextField getJmlBarang(){ return txtJumlahBarang; }
    public JTextField getTotal(){ return jTextField3; }
    public JTextField getUbay() { return jTextField4; }
    public JTextField getUkem() { return jTextField5; }
    public JTextField getJumlah(){ return jTextField3; }
    public JTextField getHargasatuan(){ return txtHargaBarang; }
    public JTextField getHargaJmlsatuan(){ return txtTotalHarga; }
    public JTextField getKodePelanggan(){ return txtKodePelanggan; }
    public JTextField getNamaPelanggan(){ return txtNamaPelanggan; }
    public JTextField getJenisObat(){ return jenisobat; }
    public JLabel getnama_admin() { return jLabel2; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void siapIsi(boolean a){;
        txtNoTf.setEnabled(a);
        txtTgl.setEnabled(a);
        jTextField3.setEnabled(a);
        jTextField4.setEnabled(a);
        jTextField5.setEnabled(a);
        txtKodeBarang.setEnabled(a);
        txtJumlahBarang.setEnabled(a);
        txtKodePelanggan.setEnabled(a);
        txtNamaPelanggan.setEnabled(a);
    }
    
    private void otomatis(){
        try {
            setKoneksi();
            String sql="select right (notrans,2)+1 from penjualan";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                rs.last();
                String no=rs.getString(1);
                while (no.length()<3){
                    no="0"+no;
                    txtNoTf.setText("S"+no);}
                }
            else
            {
                txtNoTf.setText("S001"); 
        }
        } catch (Exception e) 
        {
        }
    } 
    private void tombolNormal(){
        tambahBT.setEnabled(true);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jml1 = new javax.swing.JLabel();
        panel_form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtTgl = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtJumlahBarang = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNoTf = new javax.swing.JTextField();
        tambahBT = new javax.swing.JButton();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaBarang = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        hilangkan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtKodePelanggan = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jenisobat = new javax.swing.JTextField();
        panel_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        panel_form.setPreferredSize(new java.awt.Dimension(573, 250));
        panel_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tanggal");
        panel_form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-buying-24.png"))); // NOI18N
        jButton1.setText("Tambahkan ke Keranjang");
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_form.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 290, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kode Barang");
        panel_form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Barang");
        panel_form.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Keranjang Belanja"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 100));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-24.png"))); // NOI18N
        jButton2.setText("Batal");
        jButton2.setIconTextGap(10);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 130, -1));

        panel_form.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 450, 170));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total");
        panel_form.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jTextField3.setEditable(false);
        panel_form.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 130, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        panel_form.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jumlah Uang");
        panel_form.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Uang Kembali");
        panel_form.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jTextField5.setEditable(false);
        panel_form.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 130, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash-in-hand-24.png"))); // NOI18N
        jButton4.setText("Bayar");
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_form.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 130, -1));

        txtTgl.setEditable(false);
        panel_form.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));

        txtKodeBarang.setEditable(false);
        panel_form.add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 40, -1));

        txtJumlahBarang.setOpaque(false);
        txtJumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBarangActionPerformed(evt);
            }
        });
        txtJumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahBarangKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahBarangKeyTyped(evt);
            }
        });
        panel_form.add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, -1));

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_form.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 30, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("No. Trans");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panel_form.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        txtNoTf.setEditable(false);
        txtNoTf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNoTf.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        txtNoTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTfActionPerformed(evt);
            }
        });
        panel_form.add(txtNoTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, -1));

        tambahBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambahBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-start-24.png"))); // NOI18N
        tambahBT.setText("Mulai");
        tambahBT.setIconTextGap(10);
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });
        panel_form.add(tambahBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtNamaBarang.setEditable(false);
        panel_form.add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 94, -1));

        txtHargaBarang.setEditable(false);
        panel_form.add(txtHargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 94, -1));

        txtTotalHarga.setEditable(false);
        panel_form.add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 94, -1));

        hilangkan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hilangkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-clear-symbol-24.png"))); // NOI18N
        hilangkan.setText("Hapus");
        hilangkan.setIconTextGap(10);
        hilangkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hilangkanActionPerformed(evt);
            }
        });
        panel_form.add(hilangkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kode Pelanggan");
        panel_form.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtKodePelanggan.setOpaque(false);
        txtKodePelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodePelangganKeyReleased(evt);
            }
        });
        panel_form.add(txtKodePelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 40, -1));

        txtNamaPelanggan.setOpaque(false);
        panel_form.add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 94, -1));

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_form.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 30, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jenis Obat");
        panel_form.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jenisobat.setOpaque(false);
        panel_form.add(jenisobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 180, -1));

        panel_tabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Transaksi Penjualan"));
        panel_tabel.setPreferredSize(new java.awt.Dimension(550, 190));
        panel_tabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel_tabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 100));

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-24.png"))); // NOI18N
        jButton7.setText("Cetak");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel_tabel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-24.png"))); // NOI18N
        jButton3.setText("Buang");
        jButton3.setIconTextGap(10);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_tabel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 110, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 204));
        jLabel12.setText("Penjualan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_form, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 410, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panel_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_form, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panel_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select jumlah from barang where kode = '"+txtKodeBarang.getText()+"'");
            if (rs.next()) {
                jml1.setText(rs.getString("jumlah"));
                String jml = jml1.getText();
                int jml2 = Integer.parseInt(jml);
                int jml3 = Integer.parseInt(txtJumlahBarang.getText());
                int jml4 = jml2-jml3;
                if (jml4<0) {
                    JOptionPane.showMessageDialog(null,"Stok Barang Habis atau Tidak mencukupi","Informasi",JOptionPane.INFORMATION_MESSAGE);
                    
                } else if(jml4>=0){
                    penjualan.addtmp(this);
                    penjualan.isiTabeltmp();
                    txtJumlahBarang.setText("");
                    txtTotalHarga.setText("");
                }
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(p_pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()>=0){
            int dialogResult = JOptionPane.showConfirmDialog (this, "Anda Yakin Akan Menghapus Data Ini?","Peringatan",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                String id = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
                penjualan.deletet(id);
                penjualan.isiTabelt();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Pada Tabel Sebelum Hapus","Pesan Kesalahan",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTable2.getSelectedRow()>=0){
            String id = jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();
            String kodeb = jTable2.getValueAt(jTable2.getSelectedRow(),5).toString();
            String jmlb = jTable2.getValueAt(jTable2.getSelectedRow(),4).toString();
            penjualan.deletetmp(this,id,kodeb,jmlb);
            penjualan.isiTabeltmp();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
        int hasil = Integer.parseInt(jTextField4.getText())-Integer.parseInt(jTextField3.getText());
        jTextField5.setText(Integer.toString(hasil));
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String n = txtNoTf.getText();
        if (!jTextField5.getText().trim().isEmpty()){
            if (Integer.parseInt(jTextField5.getText())>=0){
                penjualan.simpan(this);
                penjualan.isiTabelt();
                penjualan.isiTabeltmp();
                int pesan=JOptionPane.showConfirmDialog(null, "Cetak Kwitansi Nota","Cetak",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                siapIsi(false);
                tambahBT.setText("Mulai");
                tombolNormal();
                if(pesan==JOptionPane.YES_OPTION){
                    new cetak_penjualan(n).setVisible(true);
                }else {
                    JOptionPane.showMessageDialog(null, "Simpan Transaksi Berhasil");}
                    txtNoTf.setText("");
                    txtKodeBarang.setText("");
                    txtNamaBarang.setText("");
                    txtJumlahBarang.setText("");
                    txtHargaBarang.setText("");
                    txtTotalHarga.setText("");
                    jenisobat.setText("");
                    jTextField3.setText("");
                    jTextField4.setText("");
                    jTextField5.setText("");
        
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtJumlahBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBarangKeyReleased
        // TODO add your handling code here:
        int hasil = Integer.parseInt(txtJumlahBarang.getText())*Integer.parseInt(txtHargaBarang.getText());
        txtTotalHarga.setText(Integer.toString(hasil));
    }//GEN-LAST:event_txtJumlahBarangKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new JFLBarang(this).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNoTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTfActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        // TODO add your handling code here:
        if(tambahBT.getText().equalsIgnoreCase("Mulai")){
            tambahBT.setText("Batal");
            siapIsi(true);
            otomatis();
            txtNoTf.setEnabled(false);
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);

        }else{

            siapIsi(false);
            tambahBT.setText("Mulai");
            tombolNormal();
        }
    }//GEN-LAST:event_tambahBTActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if(i== -1){
            return;
        }
        String n = (String) jTable1.getValueAt(i, 1);
        new cetak_penjualan(n).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void hilangkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hilangkanActionPerformed
        // TODO add your handling code here:
        txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtJumlahBarang.setText("");
        txtHargaBarang.setText("");
        txtTotalHarga.setText("");
        jenisobat.setText("");
        txtNamaPelanggan.setText("");
        txtKodePelanggan.setText("");
    }//GEN-LAST:event_hilangkanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new JFLPelanggan(this).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtKodePelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodePelangganKeyReleased
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
            if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
                getToolkit().beep();
                evt.consume();
            }
                String obt = txtKodePelanggan.getText();
                int obt1 = Integer.parseInt(obt);
        try {
            com.mysql.jdbc.Connection con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/apotek_1", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select * from pelanggan where kode = '"+txtKodePelanggan.getText()+"'");
            if (rs.next()) {
                txtNamaPelanggan.setText(rs.getString("nama"));
                if (obt1>0) {
                jenisobat.setText("Antibiotik");
            }
                else if(obt1==0){
                jenisobat.setText("Random");
            }
            }else{
                jenisobat.setText("Random");
                txtNamaPelanggan.setText("");
            }
            con.close();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_txtKodePelangganKeyReleased

    private void txtJumlahBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBarangKeyTyped
        // TODO add your handling code here:
        char enter=evt.getKeyChar();

        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
     
    }//GEN-LAST:event_txtJumlahBarangKeyTyped

    private void txtJumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hilangkan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jenisobat;
    private javax.swing.JLabel jml1;
    private javax.swing.JPanel panel_form;
    private javax.swing.JPanel panel_tabel;
    private javax.swing.JButton tambahBT;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtKodePelanggan;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNoTf;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/apotek_1","root","");
            st=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
void cetak_nota(){
        try {
            String NamaFile = "src/laporan/laporantransaksi.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            java.sql.Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/apotek_1","root","");
            HashMap param = new HashMap();
            param.put("ptrans",txtNoTf.getText());
            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint, true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data tidak dapat dicetak!","Cetak Data",JOptionPane.ERROR_MESSAGE);
        }
    }

    }
