/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author NABILA
 */
public class p_anggota extends javax.swing.JPanel {
    Connection con;

    /**
     * Creates new form p_anggota
     */
    public p_anggota() {
        initComponents();
        dt_anggota();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_anggota = new javax.swing.JPanel();
        jLabelanggota = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAnggota = new javax.swing.JTable();
        Cari = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jLabelanggota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelanggota.setForeground(new java.awt.Color(0, 153, 204));
        jLabelanggota.setText("Pegawai");

        tblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnggotaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblAnggota);

        Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CariKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-24.png"))); // NOI18N
        jButton3.setText("Ubah");
        jButton3.setIconTextGap(10);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-24.png"))); // NOI18N
        jButton4.setText("Hapus");
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_anggotaLayout = new javax.swing.GroupLayout(p_anggota);
        p_anggota.setLayout(p_anggotaLayout);
        p_anggotaLayout.setHorizontalGroup(
            p_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_anggotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(p_anggotaLayout.createSequentialGroup()
                .addGroup(p_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_anggotaLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_anggotaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_anggotaLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabelanggota))
                    .addGroup(p_anggotaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        p_anggotaLayout.setVerticalGroup(
            p_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_anggotaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelanggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(p_anggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnggotaMouseClicked
        // TODO add your handling code here:
        int i = tblAnggota.getSelectedRow();
        if(i== -1){
            return;
        }
        String fn = (String) tblAnggota.getValueAt(i,2);
        Cari.setText(fn);
    }//GEN-LAST:event_tblAnggotaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
                con = Koneksi.getConnection();
            String sql = "" + "SELECT * FROM login WHERE username='"+Cari.getText()+"'";
            java.sql.Statement stat=con.createStatement();
            ResultSet res=stat.executeQuery(sql);
                if(res.next()){
                    String un = res.getString("username");
                     {
                        Daftar ad = new Daftar(un);
                        ad.setVisible(true);
                        setVisible(false);
                    }
                } else {
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String un = Cari.getText();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini? '"+un+"'", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try{
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) Koneksi.getConnection().createStatement();
                statement.executeUpdate("delete from  login WHERE username='"+un+"' ");
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
            }dt_anggota();}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CariKeyReleased
        // TODO add your handling code here:
        String cari = Cari.getText();
        TableRowSorter tr = new TableRowSorter(Daftar);
        tblAnggota.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_CariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cari;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabelanggota;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel p_anggota;
    private javax.swing.JTable tblAnggota;
    // End of variables declaration//GEN-END:variables
private DefaultTableModel Daftar;
    private void dt_anggota() {
        Object kolom []={"Firstname", "Lastname","Username","password","Options"};
        Daftar=new DefaultTableModel(null,kolom);
        tblAnggota.setModel(Daftar);
        jScrollPane5.getViewport().add(tblAnggota,null);
        try {
            con = Koneksi.getConnection();
            String sql = "" + "SELECT * FROM login";
            java.sql.Statement stat=con.createStatement();
            ResultSet res=stat.executeQuery(sql);
            while (res.next()) {
                String Nama_depan=res.getString("firstname");
                String Nama_belakang=res.getString("lastname");
                String Username=res.getString("username");
                String psw=res.getString("password");
                String Option=res.getString("options");
                Object [] data={Nama_depan,Nama_belakang,Username,psw,Option};
                Daftar.addRow(data);}
            tblAnggota.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(1).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblAnggota.getColumnModel().getColumn(4).setPreferredWidth(20);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: "+ex);
        }
    }
}
